#!/usr/bin/env python3

from PySide2.QtWidgets import QApplication

from nodebot_control.ui.main_window import MainWindow
from nodebot_control.models.data_store import DataStore
from nodebot_control.devices.control_set import ControlSet
from nodebot_control.devices.joystick import Joystick
from nodebot_control.ros.executor import RosExecutor

def main(args=None):
    try:
        # setup application environment
        app = QApplication([])

        # central data store
        data = DataStore()

        # setup application components, running in a separate thread
        controls = ControlSet(data)
        controls.add(Joystick('leftStick', address = 0x48, xy_inverted = True))
        controls.add(Joystick('rightStick', address = 0x49, xy_inverted = True))

        # setup ros executor running in a separate thread
        ros_executor = RosExecutor(data)

        #setup main window
        window = MainWindow(controls, ros_executor)
        window.show()

        # run application event loop
        app.exec_()

    # final exeption handler to ensure proper shutdown of threads
    except(Exception) as e:
        print(e)
        try:
            controls.stop()
        except:
            pass
        try:
            ros_executor.stop()
        except:
            pass
        exit()


if __name__ == '__main__':
    main()
